### ISSUE TITLE
Resolve news title automatically based on the url

### ISSUE THREAD

**Issue by en237** [gixita/pulsarnews#1]
As a user, i would like the app to try to guess the title automatically based on the url of the news, so that i can submit a news even faster.

Same approach could be taken to prefill the description.

![image](https://user-images.githubusercontent.com/5197781/109955839-3bf0f680-7ce3-11eb-9804-16ed58514086.png)

**Comment by gixita** [comment]
Yes that’s a nice feature.

**Comment by gixita** [comment]
The feature is added in the feature backlog. But the description will not be added automatically as the objective is to add specific information of how it would impact the company (need to included manually by the content provider).
