### ISSUE TITLE
News publication time is not accurate

### ISSUE THREAD

**Issue by en237** [gixita/pulsarnews#2]
I just submitted a news but it shows the news has been submitted 2 days ago ?

![image](https://user-images.githubusercontent.com/5197781/109956099-8a05fa00-7ce3-11eb-951a-3cc5f62efaf1.png)

**Comment by gixita** [comment]
Yes that’s still on my todo. Currently it’s done client side. I would like
to do it server side to get rid of jquery

**Comment by gixita** [comment]
The submitted date is fixed. Still use jquery but it will changed in the future. Thank you for the issue.
